# Generated by Django 5.1.4 on 2025-06-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0024_alter_seller_companyname_alter_seller_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='order',
            field=models.JSONField(blank='True', default=list),
        ),
    ]
