# Generated by Django 5.1.4 on 2025-06-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0025_seller_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\DELL\\Desktop\\projects and learings\\ecom(Consumer working)\\E-com\\e-com\\media/seller/images'),
        ),
    ]
