# Generated by Django 5.1.4 on 2025-06-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0026_alter_seller_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seller/images/'),
        ),
    ]
