# Generated by Django 5.1.4 on 2025-06-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Beauty And Personal Care', 'Beauty And Personal Care'), ('Home And Furniture', 'Home And Furniture'), ('Sports And Outdoors', 'Sports And Outdoors'), ('Books And Stationery', 'Books And Stationery'), ('Food And Beverages', 'Food And Beverages'), ('Health And Medical', 'Health And Medical'), ('Automotive And Tools', 'Automotive And Tools'), ('Pet Supplies', 'Pet Supplies'), ('Office Products', 'Office Products'), ('Arts And Crafts', 'Arts And Crafts'), ('Baby And Kids', 'Baby And Kids'), ('Luxury And Designer', 'Luxury And Designer'), ('Books Music And Movies', 'Books Music And Movies'), ('Seasonal Products', 'Seasonal Products'), ('Travel And Luggage', 'Travel And Luggage'), ('Digital Products', 'Digital Products'), ('Gifts And Special Occasion', 'Gifts And Special Occasion'), ('Sustainability And Eco Friendly', 'Sustainability And Eco Friendly')], max_length=100),
        ),
    ]
